# Generated by Django 2.0.4 on 2018-06-04 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=50, verbose_name='идентификатор сообщения')),
                ('raw_text', models.TextField(verbose_name='текст сообщения')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='идентификатор канала')),
                ('title', models.CharField(max_length=500, verbose_name='название канала')),
            ],
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.TelegramChannel'),
        ),
    ]
